plugins {
    id 'java-library'
    id 'com.gradleup.shadow' version '9.4.1'
}

group = 'com.avrix'
version = '2.0.0'

def buildPath = System.getenv('BUILD_PATH') ?: 'build'
def baseSuffix = "Loader"
def baseArchiveName = "${rootProject.name.capitalize()}-${baseSuffix}"

repositories {
    mavenCentral()
}

dependencies {
    // Logger
    api 'org.slf4j:slf4j-api:2.0.17'
    implementation 'org.tinylog:slf4j-tinylog:2.7.0'
    implementation 'org.tinylog:tinylog-impl:2.7.0'

    // Mixin
    api 'net.lenni0451.classtransform:core:1.15.0'
    implementation 'net.lenni0451.classtransform:mixinstranslator:1.15.0'
    api 'net.lenni0451.classtransform:mixinsdummy:1.15.0'

    // Util
    api 'org.spongepowered:configurate-yaml:4.2.0'
    api 'com.github.zafarkhaja:java-semver:0.10.2'
    api 'org.jgrapht:jgrapht-core:1.5.3'

    // Test
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    filteringCharset = 'UTF-8'
    filesMatching('**/avrix.properties') {
        filter { String line ->
            line.replace('%PROJECT_VERSION%', version.toString())
                    .replace('%PROJECT_NAME%', "${rootProject.name.capitalize()} ${baseSuffix}")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set(baseArchiveName)
    archiveClassifier.set('')
    destinationDirectory.set(file(buildPath))

    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'

    manifest {
        attributes(
                'Implementation-Title': "${rootProject.name.capitalize()}-${baseSuffix}",
                'Implementation-Version': version,
                'Main-Class': 'com.avrix.Main',
                'Agent-Class': 'com.avrix.mixin.MixinAgent',
                'Can-Redefine-Classes': 'true',
                'Can-Retransform-Classes': 'true'
        )
    }
}

tasks.register('buildJar') {
    finalizedBy shadowJar
}

tasks.register('releaseBuildJar') {
    dependsOn sourceJar
    finalizedBy buildJar
}


tasks.register('sourceJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName.set(baseArchiveName)
    archiveClassifier.set('sources')
    from(sourceSets.main.allSource)
    destinationDirectory.set(file(buildPath))
}